Repository input-output-hk/cardano-explorer-app, pull requests merged in 2019-11, with the labels that each got.

#50 Continuous delivery s3
  Jenkinsfile
  README.md
  deploy/byron_incentivized_testnet.js
  deploy/byron_staging.js
  deploy/index.js
  deploy/upload.js
  package.json
  yarn.lock
Labels: enhancement

#53 [DDW-1009] Implement mainnet theme
  CHANGELOG.md
  deploy/byron_staging.js
  next.config.js
  source/styles/resources/variables-themes/variables-theme-mainnet.scss
Labels: feature

#54 [DDW-1033] Add missing SCSS variables in the mainnet theme
  CHANGELOG.md
  source/styles/resources/variables-themes/variables-theme-mainnet.scss
Labels: bug

#55 [DDW-1034] Trigger searches after component rendered
  source/features/search/components/BlocksSearchResult.tsx
  source/features/search/components/EpochsSearchResult.tsx
  source/lib/Store.ts
Labels: bug

#62 Removes the remaining traces of WEBSOCKET setup
  .env.example
  deploy/byron_incentivized_testnet.js
  deploy/byron_staging.js
  deploy/index.js
  package.json
  source/environment.ts
  yarn.lock
Labels: chore

#63 Add Network Info Feature
  generated/typings/graphql-schema.d.ts
  source/features/network-info/api/cardanoDynamic.graphql
  source/features/network-info/api/cardanoStatic.graphql
  source/features/network-info/api/index.ts
  source/features/network-info/context.ts
  source/features/network-info/index.ts
  source/features/network-info/specs/networkInfo.spec.ts
  source/features/network-info/store.ts
  source/features/network-info/ui/NetworkInfoFeatureProvider.tsx
  source/lib/Store.ts
  source/lib/react/hooks.ts
  source/pages/_app.tsx
Labels: feature

#65 Fix latest blocks slot number
  generated/typings/graphql-schema.d.ts
  source/features/blocks/api/BlockInfo.graphql
  source/features/blocks/api/transformers.ts
  source/features/blocks/types.ts
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlockSummary.tsx
  source/features/epochs/specs/helpers/latestEpochsExample.ts
  source/features/search/ui/BlockSearchResult.tsx
  stories/blocks.stories.tsx
Labels: bug

#67 Link cardano logo in header to root
  source/widgets/layout/Header.tsx
Labels: enhancement

#68 Replace header animation with static rendering
  source/features/blocks/ui/BlockSummary.scss
  source/features/search/ui/EpochsSearchResult.tsx
  source/features/search/ui/TransactionSearchResult.scss
  source/features/search/ui/TransactionSearchResult.tsx
  source/features/transactions/components/TransactionSummary.scss
  source/pages/block.tsx
  source/pages/epoch.tsx
  source/pages/index.scss
  source/pages/index.tsx
  source/pages/transaction.tsx
  source/public/assets/images/main-header-background.png
  source/public/assets/images/main-header-background@2x.png
  source/public/assets/images/main-header-background@3x.png
  source/styles/global/_reset.scss
  source/widgets/container/Container.scss
  source/widgets/layout/Footer.scss
  source/widgets/layout/Header.scss
  source/widgets/layout/Layout.scss
  source/widgets/layout/Layout.tsx
Labels: enhancement

#76 Chore/cardano graphql 0.3.0 upgrade
  CHANGELOG.md
  docker-compose.yml
  generated/typings/graphql-schema.d.ts
  next.config.js
  schema.graphql
  source/environment.ts
  source/features/blocks/api/BlockDetails.graphql
  source/features/blocks/api/BlockOverview.graphql
  source/features/blocks/api/transformers.ts
  source/features/epochs/api/EpochOverview.graphql
  source/features/epochs/api/transformers.ts
  source/features/epochs/specs/epochs.spec.ts
  source/features/network-info/store.ts
  source/features/search/specs/searchForEpochByNumber.spec.ts
  source/features/search/specs/searchForTransactionById.spec.ts
  source/features/transactions/api/transformers.ts
  source/lib/unit-converters.ts
Labels: chore

#80 Replaces global slot number with the epoch-scoped slotWithinEpoch number
  .gitignore
  Jenkinsfile
  README.md
  generated/typings/graphql-schema.d.ts
  package.json
  schema.graphql
  source/features/blocks/api/BlockDetails.graphql
  source/features/blocks/api/BlockInfo.graphql
  source/features/blocks/api/BlockOverview.graphql
  source/features/blocks/api/transformers.ts
  source/features/blocks/specs/getLatestBlocks.spec.ts
  source/features/blocks/types.ts
  source/features/blocks/ui/BlockList.tsx
  source/features/epochs/specs/helpers/latestEpochsExample.ts
  source/features/search/specs/helpers/exampleBlockData.ts
  source/features/transactions/api/TransactionDetails.graphql
  source/features/transactions/api/transformers.ts
  utils/start_dependencies.sh
  utils/start_dependencies_env_wrapper.js
Labels: bug

#83 Change endedAt to lastBlockAt in epochs
  source/features/epochs/api/transformers.ts
  source/features/epochs/specs/helpers/latestEpochsExample.ts
  source/features/epochs/types.ts
  source/features/epochs/ui/EpochList.scss
  source/features/epochs/ui/EpochList.tsx
  source/features/epochs/ui/EpochSummary.tsx
  source/pages/stake-pools.tsx
Labels: bug

#84 Only show more button when the table page is filled
  source/widgets/table/Table.tsx
Labels: bug

#85 Only show stake distribution in shelley era
  source/features/search/ui/EpochsSearchResult.tsx
Labels: bug

#91 fix/block and slot number can be null
  source/features/blocks/api/transformers.ts
  source/features/blocks/types.ts
  source/features/blocks/ui/BlockList.tsx
  source/features/transactions/components/TransactionSummary.tsx
  source/features/transactions/types.ts
Labels: bug

#94 Feature/link feed items to details pages
  .babelrc
  codegen.yml
  package.json
  source/features/blocks/ui/BlockList.tsx
  source/features/epochs/ui/EpochList.tsx
  source/features/navigation/index.ts
  source/features/navigation/store.ts
  source/features/search/store.ts
  source/features/search/ui/BlockSearchResult.tsx
  source/features/stake-pools/components/StakePools.tsx
  source/lib/ActionBinding.ts
  source/lib/Store.ts
  source/widgets/table/Table.tsx
  source/widgets/table/TableBodyRow.scss
  source/widgets/table/TableBodyRow.tsx
  stories/blocks.stories.tsx
  yarn.lock
Labels: feature

#95 Feature/tx confirmations
  .babelrc
  jest.config.js
  package.json
  source/features/search/ui/TransactionSearchResult.scss
  source/features/search/ui/TransactionSearchResult.tsx
  source/features/transactions/api/TransactionDetails.graphql
  source/features/transactions/api/transformers.ts
  source/features/transactions/components/TransactionSummary.tsx
  source/features/transactions/types.ts
  source/lib/unit-converters.ts
  stories/transactions.stories.tsx
  yarn.lock
Labels: enhancement

#96 Enable mobx strict mode
  source/config/jest.config.ts
  source/config/mobx.config.ts
  source/features/network-info/store.ts
  source/features/search/store.ts
  source/lib/graphql/GraphQLRequest.ts
  source/pages/_app.tsx
  stories/blocks.stories.tsx
Labels: chore

#97 Fix/keep latest epoch up to date
  source/features/blocks/store.ts
  source/features/epochs/index.ts
  source/features/epochs/specs/epochs.spec.ts
  source/features/epochs/store.ts
  source/features/epochs/ui/EpochsFeatureProvider.tsx
  source/lib/mobx/Reaction.ts
  source/pages/index.tsx
  wallaby.conf.js
Labels: bug

#98 Feature/address search detection
  package.json
  source/features/address/api/transformers.ts
  source/features/address/types.ts
  source/features/address/ui/AddressSummary.scss
  source/features/address/ui/AddressSummary.tsx
  source/features/blocks/api/BlockDetails.graphql
  source/features/blocks/api/BlockOverview.graphql
  source/features/blocks/types.ts
  source/features/blocks/ui/BlockList.tsx
  source/features/epochs/api/EpochDetails.graphql
  source/features/epochs/api/transformers.ts
  source/features/epochs/types.ts
  source/features/search/api/index.ts
  source/features/search/api/searchForAddress.graphql
  source/features/search/index.ts
  source/features/search/specs/helpers/exampleAddressData.ts
  source/features/search/specs/searchForAddress.spec.ts
  source/features/search/store.ts
  source/features/search/ui/AddressSearchResult.scss
  source/features/search/ui/AddressSearchResult.tsx
  source/features/search/ui/EpochsSearchResult.tsx
  source/features/search/ui/SearchBar.tsx
  source/pages/address.tsx
  stories/address.stories.tsx
  yarn.lock
Labels: enhancement

#101 Chore/optional chaining
  next.config.js
  source/features/blocks/api/transformers.ts
  source/features/epochs/api/transformers.ts
  source/features/search/specs/searchForBlockById.spec.ts
  source/features/search/specs/searchForBlockByNumber.spec.ts
  source/features/search/specs/searchForEpochByNumber.spec.ts
  source/features/search/specs/searchForTransactionById.spec.ts
  source/features/search/store.ts
  source/features/search/ui/BlockSearchResult.tsx
  source/features/search/ui/EpochsSearchResult.tsx
Labels: chore

#102 Feature/epoch percentage data
  source/features/epochs/api/transformers.ts
  source/features/epochs/specs/helpers/latestEpochsExample.ts
  source/features/epochs/store.ts
  source/features/epochs/types.ts
  source/features/epochs/ui/EpochList.tsx
  source/features/epochs/ui/EpochSummary.tsx
  source/features/network-info/api/cardanoDynamic.graphql
  source/features/network-info/store.ts
  source/features/search/index.ts
  source/features/search/specs/searchForAddress.spec.ts
  source/features/search/specs/searchForBlockById.spec.ts
  source/features/search/specs/searchForBlockByNumber.spec.ts
  source/features/search/specs/searchForEpochByNumber.spec.ts
  source/features/search/specs/searchForTransactionById.spec.ts
  source/features/search/store.ts
  source/features/search/ui/SearchFeatureProvider.tsx
  source/pages/stake-pools.tsx
  stories/blocks.stories.tsx
  stories/epochs.stories.tsx
  stories/stake-pools.stories.tsx
Labels: enhancement

#103 Wrap address search result in action runner
  source/features/search/store.ts
Labels: bug

#109 Fix/summary-page-data-navigation
  source/features/blocks/api/transformers.ts
  source/features/blocks/types.ts
  source/features/blocks/ui/BlockSummary.tsx
  source/features/epochs/ui/EpochList.tsx
  source/features/search/specs/searchForBlockByNumber.spec.ts
  source/features/search/ui/BlockSearchResult.tsx
  source/features/transactions/api/transformers.ts
  source/features/transactions/components/TransactionSummary.tsx
  source/features/transactions/types.ts
  stories/blocks.stories.tsx
  stories/transactions.stories.tsx
Labels: enhancement

#111 Fix/transaction model
  source/features/blocks/ui/BlockSummary.tsx
  source/features/navigation/index.ts
  source/features/navigation/store.ts
  source/features/search/api/searchForTransactionById.graphql
  source/features/search/specs/helpers/exampleAddressData.ts
  source/features/search/specs/searchForTransactionById.spec.ts
  source/features/search/store.ts
  source/features/search/ui/AddressSearchResult.tsx
  source/features/search/ui/TransactionSearchResult.tsx
  source/features/transactions/api/TransactionDetails.graphql
  source/features/transactions/api/transformers.ts
  source/features/transactions/components/TransactionInfo.scss
  source/features/transactions/components/TransactionInfo.tsx
  source/features/transactions/components/TransactionList.tsx
  source/features/transactions/components/TransactionSummary.tsx
  source/features/transactions/types.ts
  stories/transactions.stories.tsx
Labels: bug, enhancement

#113 Feature/block transactions
  source/features/address/ui/AddressSummary.tsx
  source/features/blocks/api/BlockDetails.graphql
  source/features/blocks/api/BlockInfo.graphql
  source/features/blocks/api/BlockOverview.graphql
  source/features/blocks/api/transformers.ts
  source/features/blocks/specs/getLatestBlocks.spec.ts
  source/features/blocks/types.ts
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlockSummary.tsx
  source/features/epochs/api/EpochDetails.graphql
  source/features/epochs/api/transformers.ts
  source/features/epochs/specs/helpers/latestEpochsExample.ts
  source/features/search/api/searchForBlockById.graphql
  source/features/search/api/searchForBlockByNumber.graphql
  source/features/search/specs/helpers/exampleBlockData.ts
  source/features/search/specs/searchForBlockById.spec.ts
  source/features/search/specs/searchForBlockByNumber.spec.ts
  source/features/search/store.ts
  source/features/search/ui/AddressSearchResult.tsx
  source/features/search/ui/BlockSearchResult.tsx
  source/features/transactions/components/TransactionList.tsx
  stories/address.stories.tsx
  stories/blocks.stories.tsx
  stories/transactions.stories.tsx
Labels: bug, enhancement

#118 Feature/no results component
  source/features/blocks/ui/BlockList.tsx
  source/features/search/api/index.ts
  source/features/search/api/searchById.graphql
  source/features/search/api/searchForBlockById.graphql
  source/features/search/index.ts
  source/features/search/specs/searchForBlockById.spec.ts
  source/features/search/specs/searchForTransactionById.spec.ts
  source/features/search/store.ts
  source/features/search/ui/AddressSearchResult.tsx
  source/features/search/ui/BlockSearchResult.tsx
  source/features/search/ui/EpochsSearchResult.tsx
  source/features/search/ui/NoSearchResult.tsx
  source/features/search/ui/SearchBar.tsx
  source/features/search/ui/TransactionSearchResult.tsx
  source/pages/no-search-results.tsx
  stories/search.stories.tsx
Labels: feature

#124 Fix/issue 93 only show no results comp when loading is done
  source/features/search/ui/AddressSearchResult.tsx
  source/features/search/ui/BlockSearchResult.tsx
  source/features/search/ui/EpochsSearchResult.tsx
  source/features/search/ui/TransactionSearchResult.tsx
  source/features/transactions/components/TransactionSummary.tsx
Labels: bug

#126 Fix broken styles loading in next.js dev mode
  source/widgets/layout/Layout.tsx
Labels: chore

#128 Fix/blocks list perf and next block
  docker-compose.yml
  source/features/blocks/api/BlockDetails.graphql
  source/features/blocks/api/BlockOverview.graphql
  source/features/blocks/api/transformers.ts
  source/features/blocks/types.ts
  source/features/blocks/ui/BlockSummary.tsx
Labels: feature, perf

#127 Fixes #123 - improve browsing params handling
  source/features/blocks/ui/BlocksBrowser.tsx
  source/features/blocks/ui/LatestBlocks.tsx
  source/features/epochs/ui/EpochsBrowser.tsx
  source/features/epochs/ui/LatestEpochs.tsx
  source/features/search/ui/EpochsSearchResult.tsx
  source/widgets/browsing/BrowseInRange.tsx
Labels: bug

#129 chore/cardano-js 0.3.0
  package.json
  source/features/address/api/transformers.ts
  source/features/search/ui/SearchBar.tsx
  source/features/transactions/api/transformers.ts
  yarn.lock
Labels: chore

#132 Fix/null and created by presentation
  source/features/blocks/api/transformers.ts
  source/features/blocks/types.ts
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlockSummary.tsx
Labels: bug, feature

#136 Fix style issues
  .storybook/webpack.config.js
  next.config.js
  package.json
  source/features/search/ui/BlockSearchResult.scss
  source/features/search/ui/BlockSearchResult.tsx
  source/features/search/ui/TransactionSearchResult.scss
  source/features/search/ui/TransactionSearchResult.tsx
  source/features/transactions/components/TransactionInfo.scss
  source/features/transactions/components/TransactionInfo.tsx
  source/pages/_app.tsx
  source/pages/index.scss
  source/pages/index.tsx
  source/public/assets/images/epoch/epoch-filled.svg
  source/public/assets/images/main-header-background.png
  source/styles/theme/CssVariablesProvider.tsx
  source/styles/theme/PolymorphThemeProvider.tsx
  source/styles/theme/theme.tsx
  source/typings/svg.modules.d.ts
  source/widgets/circular-progress/CircularProgress.scss
  source/widgets/circular-progress/CircularProgress.tsx
  source/widgets/decorators/ShowMoreButtonDecorator.scss
  source/widgets/divider-with-title/DividerWithTitle.scss
  source/widgets/layout/Footer.scss
  source/widgets/layout/Footer.tsx
  source/widgets/layout/Header.tsx
  stories/blocks.stories.tsx
  stories/epochs.stories.tsx
  yarn.lock
Labels: bug
