Repository input-output-hk/cardano-explorer-app, pull requests merged in 2019-10, with the labels that each got.

#14 [DDW-906] Organize CSS variables and structure
  .gitignore
  next.config.js
  package.json
  source/features/epochs/components/EpochInfo.scss
  source/features/epochs/components/EpochList.scss
  source/features/epochs/components/EpochListRow.scss
  source/features/shared/circular-progress/components/CircularProgress.scss
  source/features/shared/divider-with-title/components/DividerWithTitle.scss
  source/features/shared/footer/components/Footer.scss
  source/features/shared/header/components/Header.scss
  source/features/shared/search/components/Search.scss
  source/features/theme/index.global.scss
  source/layout/Head.js
  source/layout/Layout.scss
  source/layout/Layout.tsx
  source/pages/_document.tsx
  source/pages/index.tsx
  source/styles/README.md
  source/styles/global/_fonts.scss
  source/styles/global/_reset.scss
  source/styles/resources/mixins/.gitkeep
  source/styles/resources/variables-common/variables-common.scss
  source/styles/resources/variables-themes/variables-theme-incentivized-testnet.scss
  source/styles/resources/variables-themes/variables-theme-testnet.scss
  source/styles/theme/PolymorphThemeProvider.tsx
  source/styles/theme/skins.tsx
  source/styles/theme/theme.tsx
  stories/support/ThemeDecorator.tsx
  yarn.lock
Labels: feature

#18 [DDW-923] Fix Storybook configuration
  .storybook/webpack.config.js
  stories/support/ThemeDecorator.tsx
Labels: bug

#17 [DDW-889] Implement blocks component
  CHANGELOG.md
  Jenkinsfile
  source/features/blocks/components/Blocks.scss
  source/features/blocks/components/Blocks.tsx
  source/features/blocks/components/BlocksListRow.scss
  source/features/blocks/components/BlocksListRow.tsx
  source/features/blocks/containers/BlocksComponentContainer.tsx
  source/features/blocks/containers/BlocksContainer.tsx
  source/features/epochs/components/EpochInfo.tsx
  source/features/epochs/components/EpochListRow.tsx
  source/features/widgets/circular-progress/components/CircularProgress.scss
  source/features/widgets/circular-progress/components/CircularProgress.tsx
  source/features/widgets/divider-with-title/components/DividerWithTitle.scss
  source/features/widgets/divider-with-title/components/DividerWithTitle.tsx
  source/features/widgets/footer/components/Footer.scss
  source/features/widgets/footer/components/Footer.tsx
  source/features/widgets/footer/containers/FooterComponentContainer.tsx
  source/features/widgets/footer/containers/FooterContainer.tsx
  source/features/widgets/header/components/Header.scss
  source/features/widgets/header/components/Header.tsx
  source/features/widgets/header/containers/HeaderComponentContainer.tsx
  source/features/widgets/header/containers/HeaderContainer.tsx
  source/features/widgets/search/actions.ts
  source/features/widgets/search/api.ts
  source/features/widgets/search/components/Search.scss
  source/features/widgets/search/components/Search.tsx
  source/features/widgets/search/containers/SearchComponentContainer.tsx
  source/features/widgets/search/containers/SearchContainer.tsx
  source/features/widgets/search/contexts.ts
  source/features/widgets/search/graphql/getBlocks.graphql
  source/features/widgets/search/hooks.ts
  source/features/widgets/search/index.ts
  source/features/widgets/search/store.ts
  source/features/widgets/search/types.ts
  source/pages/address.tsx
  source/pages/block.tsx
  source/pages/epoch.tsx
  source/pages/error.tsx
  source/pages/index.tsx
  source/pages/outdated-browser.tsx
  source/pages/transaction.tsx
  source/styles/resources/variables-themes/variables-theme-incentivized-testnet.scss
  source/styles/resources/variables-themes/variables-theme-testnet.scss
  stories/blocks.stories.tsx
  stories/footer.stories.tsx
  stories/header.stories.tsx
  stories/search.stories.tsx
  stories/support/ThemeDecorator.tsx
Labels: feature

#22 [DDW-936] Implement address info and transaction list components
  package.json
  source/features/address/components/AddressInfo.scss
  source/features/address/components/AddressInfo.tsx
  source/features/transactions/components/TransactionList.scss
  source/features/transactions/components/TransactionList.tsx
  source/features/transactions/components/TransactionListRow.scss
  source/features/transactions/components/TransactionListRow.tsx
  source/static/assets/images/arrow-next.svg
  source/styles/resources/variables-common/variables-common.scss
  source/styles/theme/index.global.scss
  stories/address.stories.tsx
  yarn.lock
Labels: enhancement, feature

#25 [DDW-868] Implement No Search results page design
  CHANGELOG.md
  source/features/blocks/components/BlocksListRow.tsx
  source/features/epochs/components/EpochInfo.tsx
  source/features/epochs/components/EpochListRow.tsx
  source/features/widgets/circular-progress/components/CircularProgress.scss
  source/features/widgets/divider-with-title/components/DividerWithTitle.scss
  source/features/widgets/footer/components/Footer.scss
  source/features/widgets/header/components/Header.tsx
  source/features/widgets/search/components/NoSearchResult.scss
  source/features/widgets/search/components/NoSearchResult.tsx
  source/features/widgets/search/components/Search.scss
  source/static/assets/images/header/header-background.png
  source/static/assets/images/header/header-background@2x.png
  source/static/assets/images/header/header-background@3x.png
  source/styles/global/_reset.scss
  source/styles/resources/variables-common/variables-common.scss
  source/styles/resources/variables-themes/variables-theme-incentivized-testnet.scss
  source/styles/resources/variables-themes/variables-theme-testnet.scss
  stories/blocks.stories.tsx
  stories/search.stories.tsx
Labels: enhancement, feature

#27 [DDW-948] Fix merging issues from Stake Pools PR
  source/features/stake-pools/components/StakePools.tsx
  source/pages/stake-pools.tsx
Labels: bug

#24 [DDW-867] Implement Block details page design
  CHANGELOG.md
  source/features/blocks/components/BlockSummary.scss
  source/features/blocks/components/BlockSummary.tsx
  source/features/widgets/divider-with-title/components/DividerWithTitle.scss
  stories/blocks.stories.tsx
Labels: enhancement, feature

#29 [DDW-859] Unsupported Browser Notification
  next.config.js
  package.json
  source/features/address/components/AddressSummary.scss
  source/features/blocks/components/BlockList.scss
  source/features/blocks/components/BlockListRow.scss
  source/features/blocks/components/BlockSummary.scss
  source/features/epochs/components/EpochList.scss
  source/features/epochs/components/EpochListRow.scss
  source/features/epochs/components/EpochSummary.scss
  source/features/stake-pools/components/StakePoolTooltip.scss
  source/features/stake-pools/components/StakePoolTooltip.tsx
  source/features/stake-pools/components/StakePoolsList.scss
  source/features/transactions/components/TransactionInfo.scss
  source/features/transactions/components/TransactionSummary.scss
  source/features/widgets/divider-with-title/components/DividerWithTitle.scss
  source/features/widgets/footer/components/Footer.scss
  source/features/widgets/footer/components/Footer.tsx
  source/features/widgets/header/components/Header.scss
  source/features/widgets/header/components/Header.tsx
  source/features/widgets/outdated-browser/components/OutdatedBrowser.scss
  source/features/widgets/outdated-browser/components/OutdatedBrowser.tsx
  source/features/widgets/search/components/NoSearchResult.scss
  source/features/widgets/search/components/NoSearchResult.tsx
  source/features/widgets/search/components/Search.scss
  source/layout/Layout.scss
  source/layout/Layout.tsx
  source/pages/error.tsx
  source/pages/index.scss
  source/pages/outdated-browser.tsx
  source/static/assets/images/outdated-browser/chrome-gray.svg
  source/static/assets/images/outdated-browser/chrome.svg
  source/static/assets/images/outdated-browser/edge-gray.svg
  source/static/assets/images/outdated-browser/edge.svg
  source/static/assets/images/outdated-browser/firefox-gray.svg
  source/static/assets/images/outdated-browser/firefox.svg
  source/static/assets/images/outdated-browser/hub-tripple-background.svg
  source/static/assets/images/outdated-browser/opera-gray.svg
  source/static/assets/images/outdated-browser/opera.svg
  source/static/assets/images/outdated-browser/safari-gray.svg
  source/static/assets/images/outdated-browser/safari.svg
  source/styles/resources/variables-themes/variables-theme-incentivized-testnet.scss
  stories/outdated-browser.stories.tsx
  stories/stake-pools.stories.tsx
  yarn.lock
Labels: enhancement, feature

#31 [DDW-951] Fix dependencies vulnerabilities
  CHANGELOG.md
  yarn.lock
Labels: bug

#28 [DDW-914] DDW-914 Implement 'Unmoderated stake pool data warning' notification
  .storybook/webpack.config.js
  package.json
  source/features/stake-pools/actions.ts
  source/features/stake-pools/components/StakePoolsList.scss
  source/features/stake-pools/components/StakePoolsSearch.scss
  source/features/stake-pools/components/UnmoderatedDataConsented.scss
  source/features/stake-pools/components/UnmoderatedDataConsented.tsx
  source/features/stake-pools/components/UnmoderatedDataWarning.scss
  source/features/stake-pools/components/UnmoderatedDataWarning.tsx
  source/features/stake-pools/constants.ts
  source/features/stake-pools/containers/StakePoolsComponentContainer.tsx
  source/features/stake-pools/containers/StakePoolsContainer.tsx
  source/features/stake-pools/containers/UnmoderatedDataConsentedComponentContainer.js
  source/features/stake-pools/containers/UnmoderatedDataConsentedContainer.js
  source/features/stake-pools/helpers.ts
  source/features/stake-pools/index.ts
  source/features/stake-pools/store.ts
  source/features/stake-pools/types.ts
  source/features/widgets/container/components/Container.js
  source/features/widgets/container/components/Container.scss
  source/layout/Layout.tsx
  source/pages/stake-pools.tsx
  source/styles/global/_reset.scss
  stories/stake-pools.stories.tsx
  yarn.lock
Labels: enhancement

#32 [DDW-935]: Decouple search component from search blocks feature
  source/features/blocks/actions.ts
  source/features/blocks/api.ts
  source/features/blocks/containers/SearchBlockComponentContainer.tsx
  source/features/blocks/containers/SearchBlockContainer.tsx
  source/features/blocks/contexts.ts
  source/features/blocks/graphql/getBlocks.graphql
  source/features/blocks/hooks.ts
  source/features/blocks/index.ts
  source/features/blocks/store.ts
  source/features/blocks/types.ts
  source/features/widgets/header/components/Header.tsx
  source/features/widgets/header/containers/HeaderComponentContainer.tsx
  source/features/widgets/search/components/Search.tsx
  source/features/widgets/search/containers/SearchComponentContainer.tsx
  source/pages/address.tsx
  source/pages/index.tsx
  stories/header.stories.tsx
  stories/search.stories.tsx
Labels: enhancement, feature

#33 [DDW-949] Integrate the Search component into the Stake Pools page
  CHANGELOG.md
  source/features/stake-pools/components/StakePoolsSearch.scss
  source/features/stake-pools/components/StakePoolsSearch.tsx
  source/features/widgets/search/components/Search.tsx
  source/pages/index.tsx
  stories/pages.stories.tsx
Labels: feature

#34 [DDW-976] Fix styling inconsistencies
  CHANGELOG.md
  source/features/stake-pools/components/StakePoolsList.scss
  source/features/stake-pools/components/UnmoderatedDataConsented.scss
  source/features/widgets/container/components/Container.js
  source/features/widgets/container/components/Container.scss
  source/features/widgets/container/components/Container.tsx
  source/features/widgets/header/components/Header.scss
  source/features/widgets/outdated-browser/components/OutdatedBrowser.scss
  source/features/widgets/search/components/Search.scss
  source/pages/stake-pools.tsx
  source/styles/global/_fonts.scss
Labels: bug

#35 [DDW-937]: Implement pagination component
  CHANGELOG.md
  source/features/transactions/components/TransactionList.tsx
  source/features/widgets/container/components/Container.scss
  source/features/widgets/footer/components/Footer.scss
  source/features/widgets/header/components/Header.scss
  source/features/widgets/pagination/components/Pagination.scss
  source/features/widgets/pagination/components/Pagination.tsx
  source/pages/address.scss
  source/pages/address.tsx
  stories/transactions.stories.tsx
Labels: enhancement, feature

#37 [DDW-915] Add stake distribution table to the current epoch page
  CHANGELOG.md
  source/features/epochs/components/StakeDistribution.scss
  source/features/epochs/components/StakeDistribution.tsx
  source/features/epochs/components/StakeDistributionRow.scss
  source/features/epochs/components/StakeDistributionRow.tsx
  source/pages/epoch.scss
  source/pages/epoch.tsx
  stories/epochs.stories.tsx
Labels: enhancement, feature

#41 Update to latest next & next-css deps
  package.json
  source/apps/byron/index.tsx
  source/apps/shelley/index.tsx
  source/features/outdated-browser/OutdatedBrowser.tsx
  source/features/stake-pools/components/StakePoolThumbnail.tsx
  source/features/stake-pools/components/StakePoolTooltip.tsx
  source/features/transactions/components/TransactionInfo.tsx
  source/public/assets/fonts/Proxima-Nova-Bold.eot
  source/public/assets/fonts/Proxima-Nova-Bold.svg
  source/public/assets/fonts/Proxima-Nova-Bold.ttf
  source/public/assets/fonts/Proxima-Nova-Bold.woff
  source/public/assets/fonts/Proxima-Nova-Bold.woff2
  source/public/assets/fonts/Proxima-Nova-Regular.eot
  source/public/assets/fonts/Proxima-Nova-Regular.svg
  source/public/assets/fonts/Proxima-Nova-Regular.ttf
  source/public/assets/fonts/Proxima-Nova-Regular.woff
  source/public/assets/fonts/Proxima-Nova-Regular.woff2
  source/public/assets/fonts/Proxima-Nova-Semibold.eot
  source/public/assets/fonts/Proxima-Nova-Semibold.svg
  source/public/assets/fonts/Proxima-Nova-Semibold.ttf
  source/public/assets/fonts/Proxima-Nova-Semibold.woff
  source/public/assets/fonts/Proxima-Nova-Semibold.woff2
  source/public/assets/fonts/Proxima-Nova-Thin.eot
  source/public/assets/fonts/Proxima-Nova-Thin.svg
  source/public/assets/fonts/Proxima-Nova-Thin.ttf
  source/public/assets/fonts/Proxima-Nova-Thin.woff
  source/public/assets/fonts/Proxima-Nova-Thin.woff2
  source/public/assets/images/arrow-next.svg
  source/public/assets/images/epoch/epoch-filled.svg
  source/public/assets/images/facebook-icon.png
  source/public/assets/images/header/cardano-logo.svg
  source/public/assets/images/iohk-logo.png
  source/public/assets/images/main-header-background.png
  source/public/assets/images/main-header-background@2x.png
  source/public/assets/images/main-header-background@3x.png
  source/public/assets/images/main-side-background.svg
  source/public/assets/images/newsletter-icon.png
  source/public/assets/images/outdated-browser/chrome-gray.svg
  source/public/assets/images/outdated-browser/chrome.svg
  source/public/assets/images/outdated-browser/edge-gray.svg
  source/public/assets/images/outdated-browser/edge.svg
  source/public/assets/images/outdated-browser/firefox-gray.svg
  source/public/assets/images/outdated-browser/firefox.svg
  source/public/assets/images/outdated-browser/hub-tripple-background.svg
  source/public/assets/images/outdated-browser/opera-gray.svg
  source/public/assets/images/outdated-browser/opera.svg
  source/public/assets/images/outdated-browser/safari-gray.svg
  source/public/assets/images/outdated-browser/safari.svg
  source/public/assets/images/stake-pools/clock-icon.svg
  source/public/assets/images/stake-pools/close-cross.svg
  source/public/assets/images/stake-pools/link-ic.svg
  source/public/assets/images/twitter-icon.png
  source/public/assets/images/youtube-icon.png
  source/styles/global/_fonts.scss
  source/widgets/circular-progress/CircularProgress.tsx
  source/widgets/layout/Footer.tsx
  source/widgets/layout/Header.tsx
  stories/support/global.scss
  yarn.lock
Labels: enhancement

#43 [DDW-941]: Table component
  CHANGELOG.md
  source/features/blocks/components/BlockList.scss
  source/features/blocks/components/BlockList.tsx
  source/features/blocks/components/BlockListRow.scss
  source/features/blocks/components/BlockListRow.tsx
  source/features/epochs/components/EpochList.scss
  source/features/epochs/components/EpochList.tsx
  source/features/epochs/components/EpochListRow.scss
  source/features/epochs/components/EpochListRow.tsx
  source/widgets/pagination/Pagination.tsx
  source/widgets/table/Table.scss
  source/widgets/table/Table.tsx
  source/widgets/table/TableBody.scss
  source/widgets/table/TableBody.tsx
  source/widgets/table/TableBodyRow.scss
  source/widgets/table/TableBodyRow.tsx
  source/widgets/table/TableHead.scss
  source/widgets/table/TableHead.tsx
Labels: enhancement, feature

#42 [DDW-1014] Implement block search logic
  .env.example
  .env.local
  .gitignore
  Jenkinsfile
  generated/typings/graphql-schema.d.ts
  jest.config.js
  next.config.js
  package.json
  source/apps/shared/no-search-results.tsx
  source/constants.ts
  source/environment.ts
  source/features/blocks/containers/BlocksComponentContainer.tsx
  source/features/search/actions.ts
  source/features/search/api.ts
  source/features/search/components/NoSearchResult.scss
  source/features/search/components/NoSearchResult.tsx
  source/features/search/components/Search.scss
  source/features/search/components/Search.tsx
  source/features/search/containers/SearchBlockComponentContainer.tsx
  source/features/search/containers/SearchBlockContainer.tsx
  source/features/search/contexts.ts
  source/features/search/graphql/getBlocks.graphql
  source/features/search/hooks.ts
  source/features/search/index.ts
  source/features/search/specs/search.spec.ts
  source/features/search/store.ts
  source/features/search/types.ts
  source/features/stake-pools/components/StakePoolThumbnail.tsx
  source/features/stake-pools/components/StakePoolsList.tsx
  source/features/stake-pools/components/StakePoolsSearch.tsx
  source/features/stake-pools/types.ts
  source/lib/graphql/GraphQLProvider.tsx
  source/lib/graphql/GraphQLRequest.ts
  source/lib/graphql/apolloClient.ts
  source/pages/index.tsx
  source/pages/stake-pools.tsx
  source/widgets/layout/Header.tsx
  stories/search.stories.tsx
  tsconfig.json
  utils/start_dependencies_env_wrapper.js
  wallaby.conf.js
  yarn.lock
Labels: feature, work in progress

#45 Remove dependency boot script
  package.json
  utils/start_dependencies.sh
  utils/start_dependencies_env_wrapper.js
Labels: bug

#46 [DDW-1020] Setup basic search logic
  Jenkinsfile
  generated/typings/graphql-schema.d.ts
  package.json
  source/features/blocks/graphql/fragments/blockDetails.graphql
  source/features/epochs/graphql/fragments/epochDetails.graphql
  source/features/search/actions.ts
  source/features/search/api.ts
  source/features/search/containers/SearchBar.tsx
  source/features/search/containers/SearchBlockComponentContainer.tsx
  source/features/search/containers/SearchBlockContainer.tsx
  source/features/search/contexts.ts
  source/features/search/graphql/getBlocks.graphql
  source/features/search/graphql/searchForBlockById.graphql
  source/features/search/graphql/searchForBlockByNumber.graphql
  source/features/search/graphql/searchForEpochByNumber.graphql
  source/features/search/graphql/searchForTransactionById.graphql
  source/features/search/hooks.ts
  source/features/search/index.ts
  source/features/search/specs/helpers/exampleBlockData.ts
  source/features/search/specs/helpers/exampleEpochData.ts
  source/features/search/specs/helpers/exampleTransactionData.ts
  source/features/search/specs/search.spec.ts
  source/features/search/specs/searchForBlockById.spec.ts
  source/features/search/specs/searchForBlockByNumber.spec.ts
  source/features/search/specs/searchForEpochByNumber.spec.ts
  source/features/search/specs/searchForTransactionById.spec.ts
  source/features/search/store.ts
  source/features/search/types.ts
  source/features/stake-pools/store.ts
  source/features/transactions/graphql/fragments/transactionDetails.graphql
  source/lib/graphql/GraphQLRequest.ts
  source/lib/react/hooks.ts
  yarn.lock
Labels: feature

#47 [DDW-1028] Wire up index page with api data
  generated/typings/graphql-schema.d.ts
  package.json
  source/features/blocks/api/BlockOverview.graphql
  source/features/blocks/api/blockDetails.graphql
  source/features/blocks/api/getLatestBlocks.graphql
  source/features/blocks/api/index.ts
  source/features/blocks/api/transformers.ts
  source/features/blocks/index.ts
  source/features/blocks/specs/getLatestBlocks.spec.ts
  source/features/blocks/specs/helpers/latestBlocksExample.ts
  source/features/blocks/store.ts
  source/features/blocks/types.ts
  source/features/blocks/ui/BlockCreation.scss
  source/features/blocks/ui/BlockCreation.tsx
  source/features/blocks/ui/BlockCreationRow.scss
  source/features/blocks/ui/BlockCreationRow.tsx
  source/features/blocks/ui/BlockList.scss
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlockSummary.scss
  source/features/blocks/ui/BlockSummary.tsx
  source/features/blocks/ui/BlocksFeatureProvider.tsx
  source/features/blocks/ui/LatestBlocks.tsx
  source/features/epochs/api/EpochDetails.graphql
  source/features/epochs/api/getLatestEpochs.graphql
  source/features/epochs/api/index.ts
  source/features/epochs/api/transformers.ts
  source/features/epochs/index.ts
  source/features/epochs/specs/getLatestEpochs.spec.ts
  source/features/epochs/specs/helpers/latestEpochsExample.ts
  source/features/epochs/store.ts
  source/features/epochs/types.ts
  source/features/epochs/ui/EpochList.scss
  source/features/epochs/ui/EpochList.tsx
  source/features/epochs/ui/EpochSummary.scss
  source/features/epochs/ui/EpochSummary.tsx
  source/features/epochs/ui/EpochsFeatureProvider.tsx
  source/features/epochs/ui/LatestEpochs.tsx
  source/features/epochs/ui/StakeDistribution.scss
  source/features/epochs/ui/StakeDistribution.tsx
  source/features/epochs/ui/StakeDistributionRow.scss
  source/features/epochs/ui/StakeDistributionRow.tsx
  source/features/search/graphql/searchForBlockById.graphql
  source/features/search/graphql/searchForBlockByNumber.graphql
  source/features/search/graphql/searchForTransactionById.graphql
  source/features/search/specs/searchForEpochByNumber.spec.ts
  source/features/transactions/api/TransactionDetails.graphql
  source/lib/react/hooks.ts
  source/pages/epoch.tsx
  source/pages/index.tsx
  source/pages/stake-pools.tsx
  stories/blocks.stories.tsx
  stories/epochs.stories.tsx
Labels: feature

#48 [DDW-1028] Fix final issues
  jest.config.js
  package.json
  source/config/jest.config.ts
  source/features/blocks/api/BlockDetails.graphql
  source/features/blocks/specs/getLatestBlocks.spec.ts
  source/features/epochs/index.ts
  source/features/epochs/specs/getLatestEpochs.spec.ts
  source/features/epochs/store.ts
  source/features/epochs/ui/EpochsFeatureProvider.tsx
  source/features/search/components/SearchFeatureProvider.tsx
  source/features/search/containers/SearchBar.tsx
  source/features/search/index.ts
  source/features/search/specs/searchForBlockById.spec.ts
  source/features/search/specs/searchForBlockByNumber.spec.ts
  source/features/search/specs/searchForEpochByNumber.spec.ts
  source/features/search/specs/searchForTransactionById.spec.ts
  yarn.lock
Labels: bug
