Repository input-output-hk/cardano-explorer-app, pull requests merged in 2019-12, with the labels that each got.

#144 Rename staging deployment as mainnet
  Jenkinsfile
  README.md
  deploy/byron_mainnet.js
  package.json
Labels: chore

#147 Chore: Footer content legal compliance, and conformance with staking website links
  package.json
  source/widgets/layout/Footer.tsx
Labels: chore

#151 Improve client-side performance
  next.config.js
  package.json
  source/config/jest.config.ts
  source/features/address/api/transformers.ts
  source/features/blocks/api/index.ts
  source/features/blocks/api/transformers.ts
  source/features/blocks/index.ts
  source/features/blocks/specs/getLatestBlocks.spec.ts
  source/features/blocks/store.ts
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlockSummary.tsx
  source/features/blocks/ui/BlocksFeatureProvider.tsx
  source/features/epochs/api/index.ts
  source/features/epochs/index.ts
  source/features/epochs/specs/epochs.spec.ts
  source/features/epochs/store.ts
  source/features/epochs/ui/EpochList.tsx
  source/features/epochs/ui/EpochSummary.tsx
  source/features/epochs/ui/EpochsFeatureProvider.tsx
  source/features/network-info/api/index.ts
  source/features/network-info/index.ts
  source/features/network-info/specs/networkInfo.spec.ts
  source/features/network-info/store.ts
  source/features/network-info/ui/NetworkInfoFeatureProvider.tsx
  source/features/search/api/index.ts
  source/features/search/index.ts
  source/features/search/specs/searchForAddress.spec.ts
  source/features/search/specs/searchForBlockById.spec.ts
  source/features/search/specs/searchForBlockByNumber.spec.ts
  source/features/search/specs/searchForEpochByNumber.spec.ts
  source/features/search/specs/searchForTransactionById.spec.ts
  source/features/search/store.ts
  source/features/search/ui/SearchFeatureProvider.tsx
  source/features/stake-pools/api.ts
  source/features/stake-pools/components/StakePoolTooltip.tsx
  source/features/transactions/components/TransactionInfo.tsx
  source/features/transactions/components/TransactionSummary.tsx
  source/lib/graphql/GraphQLProvider.tsx
  source/lib/graphql/GraphQLRequest.ts
  source/lib/graphql/GraphQLSubscription.ts
  source/lib/graphql/apolloClient.ts
  source/lib/graphql/graphqlClient.ts
  stories/support/fake-data-helpers.ts
  yarn.lock
Labels: chore, feature

#152 Feature: Transactions browser
  source/features/address/api/transformers.ts
  source/features/address/types.ts
  source/features/blocks/index.ts
  source/features/blocks/store.ts
  source/features/blocks/ui/BlocksBrowser.tsx
  source/features/epochs/index.ts
  source/features/epochs/store.ts
  source/features/epochs/ui/EpochsBrowser.tsx
  source/features/search/api/searchForAddress.graphql
  source/features/search/specs/searchForAddress.spec.ts
  source/features/search/store.ts
  source/features/search/ui/AddressSearchResult.tsx
  source/features/search/ui/BlockSearchResult.tsx
  source/features/transactions/api/getAddressTransactions.graphql
  source/features/transactions/api/getBlockTransactions.graphql
  source/features/transactions/api/index.ts
  source/features/transactions/components/TransactionList.scss
  source/features/transactions/components/TransactionList.tsx
  source/features/transactions/components/TransactionsBrowser.scss
  source/features/transactions/components/TransactionsBrowser.tsx
  source/features/transactions/components/TransactionsFeatureProvider.tsx
  source/features/transactions/context.ts
  source/features/transactions/index.ts
  source/features/transactions/store.ts
  source/lib/paging.spec.ts
  source/lib/paging.ts
  source/pages/address.tsx
  source/pages/block.tsx
  source/widgets/browsing/BrowseInRange.tsx
  source/widgets/browsing/Pagination.tsx
  stories/transactions.stories.tsx
Labels: feature

#154 Do not link to search result epoch in block list
  source/features/blocks/ui/BlockList.scss
  source/features/blocks/ui/BlockList.tsx
  source/features/search/ui/EpochsSearchResult.tsx
  source/widgets/table/Table.tsx
  source/widgets/table/TableBodyRow.scss
  source/widgets/table/TableBodyRow.tsx
Labels: bug

#157 Issue- 114 Fix transaction info component
  source/features/transactions/components/TransactionInfo.scss
Labels: bug
