Repository input-output-hk/cardano-explorer-app, pull requests merged in 2020-01, with the labels that each got.

#155 Feature/issue 122 browse blocks on epoch page
  source/features/blocks/api/getBlocksInEpoch.graphql
  source/features/blocks/api/getLatestBlocks.graphql
  source/features/blocks/api/index.ts
  source/features/blocks/index.ts
  source/features/blocks/store.ts
  source/features/blocks/ui/BlocksBrowser.tsx
  source/features/epochs/api/EpochDetails.graphql
  source/features/epochs/api/transformers.ts
  source/features/epochs/specs/epochs.spec.ts
  source/features/epochs/types.ts
  source/features/epochs/ui/EpochSummary.tsx
  source/features/epochs/ui/EpochsBrowser.tsx
  source/features/search/api/searchForEpochByNumber.graphql
  source/features/search/specs/searchForEpochByNumber.spec.ts
  source/features/search/store.ts
  source/features/search/ui/EpochsSearchResult.tsx
  source/pages/browse-blocks.tsx
  source/pages/epoch.tsx
  source/pages/stake-pools.tsx
  source/widgets/browsing/RouterPagination.tsx
Labels: feature

#158 Fix check for fetching latest epochs
  source/features/epochs/store.ts
Labels: bug

#160 [issue-159] Separate Static and Dynamic App Parts
  package.json
  source/features/epochs/specs/helpers/latestEpochsExample.ts
  source/features/outdated-browser/BrowserUpdate.tsx
  source/features/stake-pools/containers/UnmoderatedDataConsentedComponentContainer.js
  source/lib/react/hooks.ts
  source/pages/_app.tsx
  source/pages/address.tsx
  source/pages/block.tsx
  source/pages/browse-blocks.tsx
  source/pages/browse-epochs.tsx
  source/pages/epoch.tsx
  source/pages/index.tsx
  source/pages/no-search-results.tsx
  source/pages/outdated-browser.tsx
  source/pages/stake-pools.tsx
  source/pages/transaction.tsx
  source/styles/resources/mixins/font-face.scss
  source/widgets/layout/Header.tsx
  source/widgets/layout/Layout.tsx
  source/widgets/layout/ShrinkedHeaderLayout.tsx
  yarn.lock
Labels: enhancement

#161 Fix/issue 156 reactive data transformations
  source/features/epochs/api/getLatestEpochs.graphql
  source/features/epochs/api/index.ts
  source/features/epochs/store.ts
  source/features/epochs/ui/EpochList.scss
  source/features/epochs/ui/EpochList.tsx
  source/features/epochs/ui/EpochsBrowser.tsx
  source/features/epochs/ui/LatestEpochs.tsx
  stories/epochs.stories.tsx
  stories/support/ThemeDecorator.tsx
Labels: bug

#165 [issue-162] Update and fix browser update setup
  package.json
  source/features/outdated-browser/BrowserUpdate.tsx
  yarn.lock
Labels: enhancement

#164 [issue-146] Throw on api / env network mismatch
  next.config.js
  source/environment.ts
  source/features/network-info/api/cardanoStatic.graphql
  source/features/network-info/store.ts
Labels: bug

#166 [issue-163] Use css vars for theming
  next.config.js
  package.json
  source/features/address/ui/AddressSummary.scss
  source/features/blocks/ui/BlockCreation.scss
  source/features/blocks/ui/BlockCreationRow.scss
  source/features/blocks/ui/BlockSummary.scss
  source/features/epochs/ui/EpochList.scss
  source/features/epochs/ui/EpochSummary.scss
  source/features/epochs/ui/StakeDistribution.scss
  source/features/epochs/ui/StakeDistributionRow.scss
  source/features/outdated-browser/OutdatedBrowser.scss
  source/features/search/ui/NoSearchResult.scss
  source/features/search/ui/Search.scss
  source/features/stake-pools/components/StakePoolThumbnail.scss
  source/features/stake-pools/components/StakePoolTooltip.scss
  source/features/stake-pools/components/UnmoderatedDataConsented.scss
  source/features/stake-pools/components/UnmoderatedDataWarning.scss
  source/features/transactions/components/TransactionInfo.scss
  source/features/transactions/components/TransactionSummary.scss
  source/features/transactions/components/TransactionsBrowser.scss
  source/pages/_app.tsx
  source/pages/_document.tsx
  source/styles/global/_animations.scss
  source/styles/global/_fonts.scss
  source/styles/global/_index.scss
  source/styles/global/_reset.scss
  source/styles/mixins/font-face.scss
  source/styles/resources/variables-common/variables-common.scss
  source/styles/resources/variables-themes/variables-theme-incentivized-testnet.scss
  source/styles/resources/variables-themes/variables-theme-mainnet.scss
  source/styles/resources/variables-themes/variables-theme-testnet.scss
  source/styles/theme/theme.tsx
  source/widgets/browsing/Pagination.scss
  source/widgets/circular-progress/CircularProgress.scss
  source/widgets/decorators/ShowMoreButtonDecorator.scss
  source/widgets/divider-with-title/DividerWithTitle.scss
  source/widgets/layout/Footer.scss
  source/widgets/layout/Header.scss
  source/widgets/layout/Layout.scss
  source/widgets/loading-spinner/LoadingSpinner.scss
  source/widgets/table/TableBodyRow.scss
  source/widgets/table/TableHead.scss
  stories/support/ThemeDecorator.scss
  stories/support/global.scss
  yarn.lock
Labels: chore

#167 [issue-117] Update epoch details on block height change
  source/features/blocks/ui/BlocksBrowser.tsx
  source/features/search/index.ts
  source/features/search/store.ts
  source/features/search/ui/EpochsSearchResult.tsx
Labels: enhancement

#171 [issue-170] Fix broken storybook after css refactor
  .storybook/webpack.config.js
  package.json
  source/widgets/layout/Header.tsx
  source/widgets/layout/Layout.scss
  stories/header.stories.tsx
  stories/support/ThemeDecorator.tsx
  stories/support/global.scss
  yarn.lock
Labels: bug

#172 Fix supported browsers list
  .browserslistrc
  package.json
Labels: chore

#173 [issue-168] Setup e2e testing
  Jenkinsfile
  cypress.json
  cypress/.gitignore
  cypress/cypress.webpack.config.js
  cypress/integration/latest-epochs-on-homepage.ts
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/tsconfig.json
  package.json
  stories/epochs.stories.tsx
  yarn.lock
Labels: chore

#176 [issue-169] Improve navigation feature
  source/environment.ts
  source/features/address/config.ts
  source/features/blocks/config.ts
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlockSummary.tsx
  source/features/blocks/ui/BlocksBrowser.tsx
  source/features/blocks/ui/LatestBlocks.tsx
  source/features/epochs/config.ts
  source/features/epochs/ui/EpochList.tsx
  source/features/epochs/ui/EpochsBrowser.tsx
  source/features/epochs/ui/LatestEpochs.tsx
  source/features/navigation/index.ts
  source/features/navigation/store.ts
  source/features/navigation/testing/NavigationRouterMock.ts
  source/features/navigation/ui/NavigationFeatureProvider.tsx
  source/features/outdated-browser/BrowserUpdate.tsx
  source/features/search/config.ts
  source/features/search/index.ts
  source/features/search/specs/searchForAddress.spec.ts
  source/features/search/specs/searchForBlockById.spec.ts
  source/features/search/specs/searchForBlockByNumber.spec.ts
  source/features/search/specs/searchForEpochByNumber.spec.ts
  source/features/search/specs/searchForTransactionById.spec.ts
  source/features/search/store.ts
  source/features/search/ui/AddressSearchResult.tsx
  source/features/search/ui/BlockSearchResult.tsx
  source/features/search/ui/EpochsSearchResult.tsx
  source/features/search/ui/TransactionSearchResult.tsx
  source/features/transactions/components/TransactionInfo.tsx
  source/features/transactions/components/TransactionSummary.tsx
  source/features/transactions/config.ts
  source/lib/logging.ts
  source/lib/mobx/react.ts
  source/pages/no-search-results.tsx
  source/widgets/browsing/NavigationPagination.tsx
  source/widgets/layout/Header.tsx
Labels: chore

#178 [issue-145] Update footer to new spec
  source/public/assets/images/git-icon.svg
  source/styles/theme/theme.tsx
  source/widgets/layout/Footer.scss
  source/widgets/layout/Footer.tsx
Labels: chore, styling

#179 [issue-137] Header background visual animation and static image variant
  source/public/assets/images/header/itn.png
  source/public/assets/images/header/mainnet.png
  source/public/assets/images/header/testnet.png
  source/widgets/layout/Header.scss
  source/widgets/layout/Header.tsx
Labels: chore, styling

#180 [issue-148] - Custom 404 page
  source/features/error/Error.scss
  source/features/error/Error.tsx
  source/pages/_app.tsx
  source/pages/error.scss
  source/pages/error.tsx
  source/public/assets/fonts/ChaletComprime-CologneEighty.eot
  source/public/assets/fonts/ChaletComprime-CologneEighty.svg
  source/public/assets/fonts/ChaletComprime-CologneEighty.ttf
  source/public/assets/fonts/ChaletComprime-CologneEighty.woff
  source/public/assets/fonts/ChaletComprime-CologneEighty.woff2
  source/public/assets/images/error/hub-tripple.svg
  source/widgets/layout/Footer.scss
  stories/error.stories.tsx
Labels: chore, styling

#186 Remove Incentivized Testnet theme
  source/constants.ts
  source/styles/theme/theme.tsx
  source/widgets/layout/Header.module.scss
  source/widgets/layout/Header.tsx
  stories/epochs.stories.tsx
Labels: chore
