Repository input-output-hk/cardano-explorer-app, pull requests merged in 2020-08, with the labels that each got.

#341 chore: allow/deny, include/exclude terminology
  nix/packages.nix
  release.nix
Labels: chore, devops

#338 [issue-334] Dynamically calc Byron epochs length
  .gitignore
  .graphqlconfig
  codegen.yml
  package.json
  source/features/epochs/api/transformers.ts
  source/features/network-info/api/cardanoDynamic.graphql
  source/features/network-info/api/cardanoStatic.graphql
  source/features/network-info/store.ts
  source/utils/generateGraphQLSchema.js
  yarn.lock
Labels: chore

#346 Hotfix/address search dynamic byron
  .github/workflows/tests.yml
  .gitignore
  .graphqlconfig
  CHANGELOG.md
  codegen.yml
  package.json
  source/features/blocks/api/transformers.ts
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlockSummary.tsx
  source/features/epochs/api/transformers.ts
  source/features/epochs/ui/EpochList.tsx
  source/features/epochs/ui/EpochSummary.tsx
  source/features/network-info/api/cardanoDynamic.graphql
  source/features/network-info/api/cardanoStatic.graphql
  source/features/network-info/store.ts
  source/features/search/store.ts
  source/features/search/ui/SearchBar.tsx
  source/features/stake-pools/components/StakePoolTooltip.tsx
  source/features/transactions/components/TransactionInfo.tsx
  source/utils/generateGraphQLSchema.js
  yarn.lock
Labels: bug

#347 [issue-335] Split slots & blocks into separate columns
  source/features/epochs/ui/EpochList.module.scss
  source/features/epochs/ui/EpochList.tsx
  source/features/i18n/translations/de.json
  source/features/i18n/translations/en.json
  source/features/i18n/translations/ja.json
Labels: enhancement

#348 feat: Add package.json version to footer
  next.config.js
  package.json
  source/environment.ts
  source/widgets/layout/Footer.module.scss
  source/widgets/layout/Footer.tsx
Labels: enhancement

#351 [SRE-134] Update to latest react-polymorph
  package.json
  yarn.lock
Labels: chore
