Repository input-output-hk/cardano-explorer-app, pull requests merged in 2020-03, with the labels that each got.

#220 Use cardano-graphql-ts client package for access to the schema.graphql
  .gitignore
  Jenkinsfile
  README.md
  codegen.yml
  package.json
  utils/start_dependencies.sh
  utils/start_dependencies_env_wrapper.js
  yarn.lock
Labels: devops

#221 [issue-194] Prevent searching for empty values
  source/features/search/ui/Search.tsx
Labels: bug

#222 Use the new HTTPS Cardano GraphQL endpoints
  deploy/byron_mainnet.js
  deploy/byron_testnet.js
  package.json
Labels: devops

#231 [issue-226] Add opaque bg to language options
  source/widgets/language-switcher/LanguageSwitcher.module.scss
Labels: bug

#215 Feature/refined search helper ui
  source/constants.ts
  source/features/search/ui/Search.module.scss
  source/features/search/ui/Search.tsx
  source/features/search/ui/SearchBar.tsx
  source/features/search/ui/SearchSuggestions.tsx
  source/features/stake-pools/components/StakePools.tsx
  source/features/stake-pools/components/StakePoolsSearch.tsx
  source/features/stake-pools/types.ts
  source/public/assets/images/arrow-right.svg
  source/public/assets/images/delete.svg
  stories/search.stories.tsx
Labels: enhancement, styling

#233 [issue-229] Use real links for any navigation
  source/features/address/helpers.ts
  source/features/blocks/helpers.ts
  source/features/blocks/ui/BlockList.module.scss
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlockSummary.tsx
  source/features/blocks/ui/LatestBlocks.tsx
  source/features/epochs/helpers.ts
  source/features/epochs/ui/EpochList.module.scss
  source/features/epochs/ui/EpochList.tsx
  source/features/epochs/ui/LatestEpochs.tsx
  source/features/errors/PageNotFoundError.tsx
  source/features/navigation/ui/LocalizedLink.module.scss
  source/features/navigation/ui/LocalizedLink.tsx
  source/features/search/ui/TransactionSearchResult.tsx
  source/features/stake-pools/components/UnmoderatedDataWarning.tsx
  source/features/transactions/components/TransactionInfo.module.scss
  source/features/transactions/components/TransactionInfo.tsx
  source/features/transactions/components/TransactionList.tsx
  source/features/transactions/helpers.ts
  source/widgets/decorators/ShowMoreButtonDecorator.module.scss
  source/widgets/decorators/ShowMoreButtonDecorator.tsx
  source/widgets/layout/Header.tsx
  stories/blocks.stories.tsx
Labels: bug

#230 [issue-216] Improve blocks browsing logic
  .graphqlconfig
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlocksBrowser.tsx
  source/features/epochs/config.ts
  source/features/search/ui/EpochsSearchResult.tsx
Labels: bug

#236 Cardano Explorer: Search processing improvements
  source/features/search/ui/SearchBar.tsx
Labels: enhancement

#238 Cardano Explorer. Highlighting effect for Social Media Icons
  source/widgets/layout/Footer.module.scss
  source/widgets/layout/Footer.tsx
Labels: bug, styling

#234 Fix links to epoch zero
  source/features/blocks/store.ts
  source/features/blocks/ui/BlockSummary.tsx
  source/features/search/ui/EpochsSearchResult.tsx
  source/features/transactions/components/TransactionSummary.tsx
Labels: bug

#228 Feature/complete i18n copy upgrade
  source/features/address/ui/AddressSummary.tsx
  source/features/blocks/ui/BlockCreation.tsx
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlockSummary.tsx
  source/features/blocks/ui/LatestBlocks.tsx
  source/features/blocks/ui/pages/BrowseBlocksPage.tsx
  source/features/epochs/ui/EpochList.tsx
  source/features/epochs/ui/EpochSummary.tsx
  source/features/epochs/ui/EpochsBrowser.tsx
  source/features/epochs/ui/LatestEpochs.tsx
  source/features/epochs/ui/StakeDistribution.tsx
  source/features/errors/PageNotFoundError.tsx
  source/features/i18n/store.ts
  source/features/i18n/translations/404/de.json
  source/features/i18n/translations/404/en.json
  source/features/i18n/translations/404/ja.json
  source/features/i18n/translations/de.json
  source/features/i18n/translations/en.json
  source/features/i18n/translations/ja.json
  source/features/outdated-browser/OutdatedBrowser.tsx
  source/features/outdated-browser/OutdatedBrowserPage.tsx
  source/features/search/ui/AddressSearchResult.tsx
  source/features/search/ui/BlockSearchResult.tsx
  source/features/search/ui/EpochsSearchResult.tsx
  source/features/search/ui/NoSearchResult.tsx
  source/features/search/ui/TransactionSearchResult.tsx
  source/features/search/ui/pages/NoSearchResultPage.tsx
  source/features/stake-pools/components/StakePoolTooltip.tsx
  source/features/stake-pools/components/StakePools.tsx
  source/features/stake-pools/components/StakePoolsSearch.tsx
  source/features/stake-pools/components/UnmoderatedDataConsented.tsx
  source/features/stake-pools/components/UnmoderatedDataWarning.tsx
  source/features/transactions/components/TransactionSummary.tsx
  source/features/transactions/components/TransactionsBrowser.tsx
  source/pages/[locale]/no-search-results.tsx
  source/widgets/browsing/Pagination.tsx
  source/widgets/layout/Footer.tsx
  source/widgets/layout/Header.tsx
  source/widgets/table/TableHead.tsx
Labels: feature, work in progress

#244 [issue-216] Reverse list in blocks browsers
  source/features/blocks/ui/BlocksBrowser.tsx
Labels: bug

#245 [issue-241] Show loading state for manual browsing
  source/features/blocks/ui/BlocksBrowser.tsx
  source/widgets/browsing/NavigationPagination.tsx
Labels: enhancement

#246 Optimize build with Next.js 9.3 and preact
  next.config.js
  package.json
  source/features/i18n/store.ts
  source/public/assets/images/header/mainnet.png
  source/public/assets/images/header/testnet.png
  yarn.lock
Labels: enhancement

#253 [issue 248] - Explorer's Tab is missing key when Japanese is selected
  source/features/i18n/translations/404/ja.json
  source/features/i18n/translations/ja.json
Labels: bug

#258 [issue 249] - Adding missing translations for No results page
  source/features/i18n/translations/de.json
  source/features/i18n/translations/en.json
  source/features/i18n/translations/ja.json
  source/features/search/ui/pages/NoSearchResultPage.tsx
Labels: bug

#254 Fix/mobile fixes
  source/features/i18n/translations/de.json
  source/features/i18n/translations/en.json
  source/features/landing-page/LandingPage.module.scss
  source/features/search/ui/Search.module.scss
  source/features/transactions/components/TransactionInfo.module.scss
  source/features/transactions/components/TransactionInfo.tsx
  source/widgets/layout/Footer.module.scss
  source/widgets/layout/Header.module.scss
Labels: bug, styling

#261 Fix/issue 257 epoch lists reversed
  next.config.js
  package.json
  source/features/epochs/store.ts
  source/features/epochs/ui/EpochList.tsx
  yarn.lock
Labels: bug

#266 [issue-265] Fix order of epochs browser
  source/features/epochs/ui/EpochsBrowser.tsx
Labels: bug

#255 [issue-251] - Missing Translations/Key - German/Japanese
  source/features/i18n/translations/404/ja.json
  source/features/i18n/translations/ja.json
Labels: bug, styling

#267 [issue-264] Do not translate the locale picker
  source/features/i18n/translations/de.json
  source/features/i18n/translations/en.json
  source/features/i18n/translations/ja.json
Labels: bug

#259 [issue 250] - Text wrapping for different languages
  source/features/blocks/ui/BlockList.module.scss
  source/features/epochs/ui/EpochList.module.scss
  source/features/i18n/translations/de.json
  source/widgets/layout/Footer.module.scss
Labels: bug

#269 [issue-240] Fix latest epoch circle animation in Firefox
  package.json
  source/public/assets/images/epoch/ouroboros-spinning-gradient.png
  source/public/assets/images/epoch/ouroboros-spinning-gradient@2x.png
  source/styles/theme/theme.tsx
  source/widgets/circular-progress/CircularProgress.module.scss
  yarn.lock
Labels: bug

#270 [issue 252] - Search/Epoch navigation stalled
  source/features/search/ui/EpochsSearchResult.tsx
Labels: bug

#275 [issue 274]- Fixing issues with missing translations
  source/features/i18n/translations/de.json
  source/features/i18n/translations/ja.json
Labels: bug

#276 [issue 273] - Fixing issues with missing translations
  source/features/i18n/translations/ja.json
Labels: bug

#279 [issue 271] - Remove Epoch/Slot Links on the opened page
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlocksBrowser.tsx
Labels: bug

#281 [issue-268] Simplify and improve blocks browser
  source/features/blocks/api/transformers.ts
  source/features/blocks/store.ts
  source/features/blocks/ui/BlocksBrowser.tsx
  source/features/epochs/store.ts
  source/features/search/store.ts
  source/features/transactions/store.ts
  source/lib/AbortablePromise.ts
  source/lib/graphql/GraphQLRequest.ts
  source/lib/mobx/react.ts
  source/lib/types.ts
Labels: bug
