Repository input-output-hk/cardano-explorer-app, pull requests merged in 2020-02, with the labels that each got.

#187 [issue-137] Header background visual animation and static image variant
  source/features/blocks/ui/BlockList.module.scss
  source/features/errors/ErrorPage.module.scss
  source/features/errors/ErrorPage.tsx
  source/features/errors/PageNotFoundError.module.scss
  source/features/errors/PageNotFoundError.tsx
  source/features/search/ui/Search.module.scss
  source/pages/index.module.scss
  source/pages/index.tsx
  source/public/assets/fonts/ChaletComprime-CologneEighty.woff2
  source/public/assets/fonts/ChaletComprime.woff
  source/public/assets/fonts/Proxima-Nova-Light.woff2
  source/public/assets/images/header/itn.png
  source/styles/global/fonts.scss
  source/styles/theme/theme.tsx
  source/widgets/container/Container.module.scss
  source/widgets/layout/Footer.module.scss
  source/widgets/layout/Header.module.scss
  source/widgets/layout/Header.tsx
  source/widgets/layout/Layout.module.scss
  stories/error.stories.tsx
Labels: bug, styling

#188 Fixing storybook font loading
  .storybook/webpack.config.js
  package.json
Labels: bug

#206 Fix/issue 201 - Search bar and button style
  source/features/search/ui/Search.module.scss
  source/widgets/layout/Header.module.scss
Labels: bug, styling

#207 Fixing issue 199 - Header text is not a home link target
  source/widgets/layout/Header.module.scss
  source/widgets/layout/Header.tsx
Labels: bug, styling

#209 Fixing issue 198 - Footer fixes
  source/widgets/layout/Footer.module.scss
Labels: bug, styling

#208 Fixing issue 195 - Pagination arrow hover styling
  source/widgets/browsing/Pagination.module.scss
  source/widgets/browsing/Pagination.tsx
Labels: bug, styling

#210 Fixing issue 196 - Erroneous subheading on homepage, invalid styling of the downward arrow element
  source/widgets/layout/Header.module.scss
  source/widgets/layout/Header.tsx
Labels: bug, styling

#212 Fix: Dont use external urls with next.js Link
  source/features/errors/PageNotFoundError.tsx
  source/widgets/layout/Footer.tsx
Labels: bug

#211 Fixing issue 200 - Outdated Browser page styling and missing footer
  source/features/outdated-browser/OutdatedBrowser.module.scss
  source/pages/outdated-browser.tsx
  stories/outdated-browser.stories.tsx
Labels: bug, styling

#213 Fixing issue 197 - Component misalignment
  source/features/search/ui/Search.module.scss
  source/features/search/ui/Search.tsx
  source/styles/theme/theme.tsx
Labels: bug, styling

#205 Fixing issue 202 - Erroneous space after ellipsis in long address display
  .nvmrc
  source/features/transactions/components/TransactionInfo.module.scss
  source/features/transactions/components/TransactionInfo.tsx
Labels: bug, styling

#218 Search button looses highlighting effect if cursor if moved out while button still pressed
  source/features/search/ui/Search.module.scss
Labels: bug, styling

#214 Multi language ui component
  source/constants.ts
  source/styles/theme/theme.tsx
  source/widgets/language-switcher/LanguageSwitcher.module.scss
  source/widgets/language-switcher/LanguageSwitcher.tsx
  stories/language-switcher.stories.tsx
Labels: enhancement, feature, styling
