Repository input-output-hk/cardano-explorer-app, pull requests merged in 2020-07, with the labels that each got.

#315 Fix prettier formatting
  source/environment.ts
  source/features/blocks/ui/BlockList.tsx
  source/features/epochs/ui/EpochList.tsx
  source/features/i18n/store.ts
  source/features/outdated-browser/OutdatedBrowser.tsx
  source/features/search/ui/Search.tsx
  source/features/search/ui/SearchBar.tsx
  source/features/transactions/api/transformers.ts
  source/lib/AbortablePromise.ts
  source/lib/Action.ts
  source/lib/ActionBinding.ts
  source/lib/StatefulRequest.ts
  source/lib/Store.ts
  source/lib/colors.ts
  source/lib/enums.ts
  source/lib/logging.ts
  source/lib/mobx/Reaction.ts
  source/styles/theme/CssVariablesProvider.tsx
  source/widgets/browsing/Pagination.tsx
  source/widgets/language-switcher/LanguageSwitcher.tsx
  source/widgets/layout/Layout.tsx
  source/widgets/table/TableBody.tsx
  stories/epochs.stories.tsx
  stories/search.stories.tsx
  stories/stake-pools.stories.tsx
Labels: chore

#316 [issue-302] Cleanup footer links
  source/features/i18n/translations/de.json
  source/features/i18n/translations/en.json
  source/features/i18n/translations/ja.json
  source/widgets/layout/Footer.tsx
Labels: bug

#317 [issue-232] Fix strange reloading in dev env
  next.config.js
  source/features/address/config.ts
  source/features/blocks/config.ts
  source/features/epochs/config.ts
  source/features/errors/PageNotFoundError.tsx
  source/features/search/config.ts
  source/features/stake-pools/components/UnmoderatedDataWarning.tsx
  source/features/transactions/config.ts
  source/widgets/layout/Header.tsx
Labels: bug

#314 [issue-306] Upgrade to Next.js 9.4
  .nvmrc
  next.config.js
  package.json
  source/features/blocks/ui/BlocksBrowser.tsx
  source/features/epochs/ui/EpochsBrowser.tsx
  source/features/i18n/translations/de.json
  source/features/navigation/index.ts
  source/features/navigation/store.ts
  source/features/search/ui/EpochsSearchResult.tsx
  source/features/transactions/components/TransactionInfo.tsx
  source/pages/_app.tsx
  tsconfig.json
  yarn.lock
Labels: bug, chore

#318 Update to conform with Cardano GraphQL 1.0.0-rc.13 changes
  .graphqlconfig
  codegen.yml
  package.json
  source/config/jest.config.ts
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlockSummary.tsx
  source/features/epochs/ui/EpochList.tsx
  source/features/epochs/ui/EpochSummary.tsx
  source/features/network-info/api/cardanoDynamic.graphql
  source/features/network-info/api/cardanoStatic.graphql
  source/features/network-info/specs/networkInfo.spec.ts
  source/features/network-info/store.ts
  source/features/search/specs/searchForBlockById.spec.ts
  source/features/stake-pools/components/StakePoolTooltip.tsx
  source/features/transactions/components/TransactionInfo.tsx
  yarn.lock
Labels: chore, enhancement

#320 Bump `cardano-graphql` dep to `1.0.0`,
  CHANGELOG.md
  README.md
  deploy/byron_testnet.js
  deploy/example_deployment.js
  deploy/index.js
  deploy/upload.js
  package.json
  source/environment.ts
  yarn.lock
Labels: chore, documentation

#326 Compatibility update for Cardano GraphQL 2.0.0
  .env.example
  README.md
  codegen.yml
  package.json
  source/environment.ts
  source/features/blocks/api/BlockOverview.graphql
  source/features/blocks/api/transformers.ts
  source/features/network-info/api/cardanoDynamic.graphql
  source/features/network-info/api/cardanoStatic.graphql
  source/features/network-info/specs/networkInfo.spec.ts
  source/features/network-info/store.ts
  source/features/transactions/api/TransactionDetails.graphql
  yarn.lock
Labels: chore, dependencies

#327 fix: Hardens the slot leader formatting
  source/features/blocks/api/transformers.ts
  source/features/search/specs/searchForBlockById.spec.ts
Labels: bug

#331 chore: minor changes to support cardano-graphql 2.0.0
  .github/workflows/tests.yml
  package.json
  source/features/blocks/api/BlockOverview.graphql
  source/features/blocks/api/transformers.ts
  source/features/network-info/api/cardanoDynamic.graphql
  source/features/network-info/store.ts
  source/features/transactions/api/transformers.ts
  source/features/transactions/components/TransactionInfo.tsx
  source/features/transactions/types.ts
  yarn.lock
Labels: chore

#332 fix: Detect era to accurately display slot length
  CHANGELOG.md
  package.json
  source/features/epochs/api/EpochOverview.graphql
  source/features/epochs/api/transformers.ts
  source/features/network-info/specs/networkInfo.spec.ts
  source/features/network-info/store.ts
Labels: bug

#337 re-enable ci testing
  .github/workflows/tests.yml
Labels: chore

#339 Fixes prettier formatting
  source/features/blocks/api/transformers.ts
  source/features/blocks/ui/BlockList.tsx
  source/features/blocks/ui/BlockSummary.tsx
  source/features/epochs/api/transformers.ts
  source/features/epochs/ui/EpochList.tsx
  source/features/epochs/ui/EpochSummary.tsx
  source/features/stake-pools/components/StakePoolTooltip.tsx
  source/features/transactions/components/TransactionInfo.tsx
Labels: chore
